"""
services/disclaimer_service.py - 开发者免责协议服务
包含完整的免责协议文本，以及版本管理
"""
from datetime import datetime
from typing import Optional


# ============================================================
# 当前协议版本（每次修改协议内容时更新）
# ============================================================
CURRENT_DISCLAIMER_VERSION = "v1.0"
DISCLAIMER_EFFECTIVE_DATE = "2026年5月17日"


# ============================================================
# 完整免责协议文本（中文）
# ============================================================

DISCLAIMER_TEXT_CN = f"""
【催催侠 - 开发者服务免责协议】

（以下简称"本服务"）

发布日期：{DISCLAIMER_EFFECTIVE_DATE}
协议版本：{CURRENT_DISCLAIMER_VERSION}

请您在使用本服务之前，仔细阅读并理解本协议的全部内容。
如您不同意本协议的任何内容，请不要注册或使用本服务。
您的注册行为将被视为您已充分理解并自愿接受本协议的全部约束。

---

一、服务性质声明

1.1 本服务是由个人开发者（以下简称"开发者"）无偿搭建并提供的
   工具服务，旨在帮助自由职业者管理应收账款和催款流程。

1.2 本服务以"现状"（AS IS）和"按可用"（AS AVAILABLE）为基础提供，
   开发者不对本服务的准确性、完整性、可靠性、及时性作出任何明示或
   默示的保证或承诺。

1.3 开发者有权随时修改、中断、暂停或终止本服务的全部或部分功能，
   无需事先通知用户。

---

二、AI 生成内容的免责声明

2.1 本服务中的催款话术由人工智能（AI）模型自动生成，
   仅供用户参考使用，不代表开发者的立场或法律意见。

2.2 AI 生成的话术内容可能存在以下风险：
   • 语气、措辞可能不符合用户的预期或客户的接受程度
   • 可能不适用于所有行业、职业或地区的商务习惯
   • 可能存在语法错误、表达歧义或法律风险

2.3 用户在使用 AI 生成的话术前，应自行判断其适当性。
   对于任何因使用 AI 生成话术而导致的：
   • 客户关系恶化或破裂
   • 商业机会损失
   • 法律纠纷或诉讼
   • 声誉或经济损失

   开发者不承担任何直接或间接责任。

---

三、法律合规责任

3.1 用户应自行确保其催款行为符合以下要求：
   • 适用的法律法规（包括但不限于《民法典》《劳动合同法》等）
   • 行业规范和商业道德
   • 客户合同中的约定条款

3.2 严禁将本服务用于以下用途：
   • 骚扰、威胁、恐吓债务人
   • 发送垃圾信息或违法广告
   • 侵犯他人隐私或知识产权
   • 进行任何形式的诈骗、欺诈或非法催收
   • 其他违反法律法规或公序良俗的行为

3.3 如因用户违反上述规定而导致第三方投诉、追责或法律后果，
   由用户自行承担全部责任，开发者无需承担任何连带责任。

---

四、数据安全与隐私

4.1 开发者承诺采取合理的技术和管理措施保护用户数据安全，
   但不对数据丢失、泄露或损坏承担任何责任。

4.2 用户应妥善保管自己的账号和密码，因账号被盗用而导致的一切后果，
   由用户自行承担。

4.3 本服务的数据存储基于第三方云平台（Supabase），
   开发者不对第三方平台的服务质量、数据安全承担保证责任。

---

五、第三方服务

5.1 本服务可能包含指向第三方网站或服务的链接，
   用户自行决定是否访问或使用第三方服务。

5.2 第三方服务（包括但不限于 DeepSeek AI、微信支付等）的：
   • 服务质量
   • 可用性
   • 收费策略
   • 数据处理方式

   均由第三方自行负责，开发者不对上述事项承担任何责任。

---

六、责任限制

6.1 在任何情况下，开发者因本服务而产生的累计赔偿责任，
   以用户为该等服务向开发者实际支付的金额（如有）为限。

6.2 对于以下损失，开发者不承担任何赔偿责任：
   • 间接损失、附带损失、惩罚性赔偿或后果性损失
   • 利润损失、营业收入损失、业务机会损失
   • 数据丢失或损坏
   • 第三方索赔

   即使开发者已被告知发生此类损失的可能性。

---

七、协议变更

7.1 开发者有权随时修改本协议，修改后的协议版本号将递增
   （如 v1.0 → v1.1）。

7.2 如协议有重大变更，开发者将通过本服务界面公告的方式通知用户。

7.3 用户在协议变更后继续使用本服务，视为接受变更后的协议。
   如用户不同意变更，应停止使用本服务并注销账号。

---

八、争议解决

8.1 本协议的订立、执行和解释均适用中华人民共和国法律。

8.2 因本协议引起的或与之相关的任何争议，
   应提交有管辖权的人民法院诉讼解决。

---

九、其他

9.1 本协议的任何条款因任何原因被认定无效或不可执行，
   不影响其他条款的效力和执行。

9.2 本协议采用中文文本，如与英文翻译版本有任何冲突，
   以中文文本为准。

---

如您同意以上全部条款，请勾选"我已阅读并同意《开发者服务免责协议》"后完成注册。
"""


# ============================================================
# 英文版本（供外籍用户参考）
# ============================================================

DISCLAIMER_TEXT_EN = f"""
[ChuiChuiXia - Developer Service Disclaimer]

Version: {CURRENT_DISCLAIMER_VERSION}
Effective Date: {DISCLAIMER_EFFECTIVE_DATE}

---

IMPORTANT NOTICE:

This service is provided by an independent individual developer
on an "AS IS" and "AS AVAILABLE" basis without any warranties.

1. AI-GENERATED CONTENT
   Reminder messages are generated by AI and are for reference only.
   The developer does not guarantee accuracy, appropriateness,
   or legal compliance of AI-generated content.
   Users are solely responsible for reviewing and approving
   any messages before sending them to clients.

2. LEGAL COMPLIANCE
   Users are solely responsible for ensuring their collection
   practices comply with applicable laws and regulations.
   This service must not be used for harassment, threats,
   spam, fraud, or any illegal activities.

3. THIRD-PARTY SERVICES
   Third-party services (AI providers, payment processors, etc.)
   are subject to their own terms and policies.
   The developer is not responsible for third-party services.

4. LIABILITY LIMITATION
   The developer's total liability shall not exceed the amount
   actually paid by the user for this service (if any).
   The developer shall not be liable for indirect, incidental,
   special, or consequential damages.

5. CHANGES TO THIS AGREEMENT
   The developer may modify this agreement at any time.
   Continued use of the service constitutes acceptance.

By registering and using this service, you acknowledge that
you have read, understood, and agree to be bound by this disclaimer.
"""


# ============================================================
# 服务函数
# ============================================================

def get_disclaimer(language: str = "zh") -> dict:
    """
    获取免责协议内容

    Args:
        language: 语言代码，"zh" = 中文，"en" = 英文

    Returns:
        dict: 包含协议版本、日期和全文
    """
    text = DISCLAIMER_TEXT_CN if language == "zh" else DISCLAIMER_TEXT_EN

    return {
        "version": CURRENT_DISCLAIMER_VERSION,
        "effective_date": DISCLAIMER_EFFECTIVE_DATE,
        "language": language,
        "content": text.strip(),
        "total_chars": len(text),
    }


def validate_agreement(agreed_version: str) -> bool:
    """
    验证用户同意的协议版本是否有效

    Args:
        agreed_version: 用户同意的协议版本号

    Returns:
        bool: True = 有效，False = 版本过期
    """
    return agreed_version == CURRENT_DISCLAIMER_VERSION
